CREATE TABLE UTILISATEUR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PWD VARCHAR(100) NOT NULL,
    ACTIF TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE PROFIL (
    ID BIGINT PRIMARY KEY,
    FULLNAME VARCHAR(100) NOT NULL,
    METIER VARCHAR(100) NOT NULL,
    UTILISATEUR_ID BIGINT NOT NULL UNIQUE,
    CONSTRAINT FK_PROFIL_UTILISATEUR
        FOREIGN KEY (UTILISATEUR_ID)
        REFERENCES UTILISATEUR(ID)
);

CREATE TABLE PROJET (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PROJET_NAME VARCHAR(100) NOT NULL UNIQUE,
    PROJET_DESCRIPTION VARCHAR(200) NOT NULL,
    CREATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROJET_STATUS VARCHAR(20) NOT NULL DEFAULT 'TODO',
    OWNER_ID BIGINT NOT NULL,
    CONSTRAINT FK_PROJET_OWNER
        FOREIGN KEY (OWNER_ID)
        REFERENCES UTILISATEUR(ID)
);

CREATE TABLE TICKET (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL UNIQUE,
    TICKET_DESCRIPTION VARCHAR(200) NOT NULL,
    TICKET_STATUS VARCHAR(20) NOT NULL DEFAULT 'TODO',
    TICKET_PRIORITY VARCHAR(20) NOT NULL DEFAULT 'LOW',
    CREATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DEADLINE DATE,
    PROJET_ID BIGINT NOT NULL,
    CREATOR_ID BIGINT NOT NULL,
    ASSIGNE_ID BIGINT,
    CONSTRAINT FK_TICKET_PROJET
        FOREIGN KEY (PROJET_ID)
        REFERENCES PROJET(ID),
    CONSTRAINT FK_TICKET_CREATOR
        FOREIGN KEY (CREATOR_ID)
        REFERENCES UTILISATEUR(ID),
    CONSTRAINT FK_TICKET_ASSIGNE
        FOREIGN KEY (ASSIGNE_ID)
        REFERENCES UTILISATEUR(ID)
);

CREATE TABLE COMMENTAIRE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CONTENU VARCHAR(500) NOT NULL,
    CREATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AUTEUR_ID BIGINT NOT NULL,
    TICKET_ID BIGINT NOT NULL,
    CONSTRAINT FK_COMMENTAIRE_AUTEUR
        FOREIGN KEY (AUTEUR_ID)
        REFERENCES UTILISATEUR(ID),
    CONSTRAINT FK_COMMENTAIRE_TICKET
        FOREIGN KEY (TICKET_ID)
        REFERENCES TICKET(ID)
);

CREATE TABLE TAG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TICKET_TAG (
    TICKET_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,
    CONSTRAINT PK_TICKET_TAG
        PRIMARY KEY (TICKET_ID, TAG_ID),
    CONSTRAINT FK_TICKET_TAG_TICKET
        FOREIGN KEY (TICKET_ID)
        REFERENCES TICKET(ID),
    CONSTRAINT FK_TICKET_TAG_TAG
        FOREIGN KEY (TAG_ID)
        REFERENCES TAG(ID)
);